[package]
name = "spl-message-executor-interface"
version = "0.1.0"
description = "Interface for the SPL Message Executor program"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[package.metadata.solana]
program-id = "ExecxgyHYsAXB4c5dZodV1zJZ9hqfsDCYkRDRATrpkFR"

[lints]
workspace = true

[dependencies]
solana-address = { workspace = true, features = ["decode"] }
solana-message = { workspace = true, features = ["wincode"] }
solana-program-error = { workspace = true }
wincode = { workspace = true, features = ["derive"] }
