[workspace]
resolver = "2"
members = [
    "clients/cli",
    "executor/client",
    "executor/interface",
    "executor/program",
    "nonce/client",
    "nonce/interface",
    "nonce/program",
    "signer/client",
    "signer/interface",
    "signer/program",
]

[workspace.package]
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/nonce"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.104"
brine-ed25519 = "0.7.0"
clap = "3.2.25"
codama-macros = "0.13.1"
mollusk-svm = "0.15.0"
pinocchio = { version = "0.11.2", default-features = false }
serde = "1.0.229"
serde_json = "1.0.151"
solana-account = "4.3.0"
solana-address = "2.6.1"
solana-clap-v3-utils = "4.2.1"
solana-cli-config = "4.2.1"
solana-commitment-config = "3.1.1"
solana-hash = "4.4.0"
solana-instruction = { version = "3.4.0", default-features = false }
solana-keypair = "3.1.2"
solana-message = { version = "4.4.0", default-features = false }
solana-native-token = "3.0.0"
solana-program-error = "3.0.1"
solana-rent = "4.2.0"
solana-rpc-client = { version = "4.2.1", default-features = false }
solana-sanitize = "3.0.1"
solana-sdk-ids = "3.1.0"
solana-sha256-hasher = "3.1.0"
solana-signature = { version = "3.4.1", default-features = false }
solana-signer = { version = "3.0.1", default-features = false }
solana-system-interface = "3.2.0"
solana-transaction = { version = "4.1.3", default-features = false }
test-case = "3.3.1"
tokio = "1.53.1"
wincode = { version = "0.5.5", default-features = false }

spl-ed25519-signer-client = { path = "signer/client" }
spl-ed25519-signer-interface = { path = "signer/interface" }
spl-legacy-message-executor-client = { path = "executor/client" }
spl-legacy-message-executor-interface = { path = "executor/interface" }
spl-nonce-client = { path = "nonce/client" }
spl-nonce-interface = { path = "nonce/interface" }

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("custom-alloc", "custom-heap", "custom-panic", "frozen-abi", "no-entrypoint"))',
]

[workspace.metadata.spellcheck]
config = "scripts/spellcheck.toml"
