[package]
name = "spl-ed25519-signer-program"
version = "0.1.0"
description = "SPL Ed25519 Signer program"
authors = {workspace = true}
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.solana]
program-id = "EdSigVfK1DkeMrjFNDMjwfQaJPhPTtX7jW8uPv3oKEgN"

[lints]
workspace = true

[dependencies]
brine-ed25519 = { workspace = true }
pinocchio = { workspace = true, features = ["alloc", "cpi"] }
solana-message = { workspace = true, features = ["wincode"] }
solana-transaction = { workspace = true, features = ["wincode"] }
spl-ed25519-signer-interface = { workspace = true }

[dev-dependencies]
mollusk-svm = { workspace = true }
solana-account = { workspace = true }
solana-address = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-program-error = { workspace = true }
solana-signer = { workspace = true }
solana-system-interface = { workspace = true, features = ["wincode"] }
spl-ed25519-signer-client = { workspace = true }
test-case = { workspace = true }
