[package]
name = "spl-ed25519-programmatic-signer-legacy-interface"
version = "0.1.0"
description = "Interface for the SPL Ed25519 Programmatic Signer program"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[package.metadata.solana]
program-id = "EdSigVfK1DkeMrjFNDMjwfQaJPhPTtX7jW8uPv3oKEgN"

[lints]
workspace = true

[dependencies]
solana-address = { workspace = true, features = ["curve25519", "decode", "wincode"] }
solana-hash = { workspace = true }
solana-program-error = { workspace = true }
wincode = { workspace = true, features = ["derive"] }
