[package]
name = "spl-nonce-interface"
version = "0.1.0"
description = "Interface for the SPL Nonce program"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[package.metadata.solana]
program-id = "nonce34S3Viw97xQwWGpRWEGufiSpfVEAiFe7Lefv7y"

[lints]
workspace = true

[dependencies]
solana-address = { version = "2.6.0", features = ["curve25519", "decode", "wincode"] }
solana-hash = { version = "4.3.0", features = ["wincode"] }
wincode = { version = "0.5.3", features = ["derive"] }
