[package]
name = "spl-nonce-program"
version = "0.1.0"
description = "TBD"
authors = {workspace = true}
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[lib]
crate-type = ["cdylib"]

[package.metadata.solana]
program-id = "nonce34S3Viw97xQwWGpRWEGufiSpfVEAiFe7Lefv7y"

[lints]
workspace = true

[dependencies]


[dev-dependencies]
