[package]
name = "spl-nonce-program"
version = "0.1.0"
description = "SPL Nonce program"
authors = {workspace = true}
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[lib]
crate-type = ["cdylib"]

[package.metadata.solana]
program-id = "Noncediea1fH12usShuQAz28UhgAeuE5Maf32LsMUQB"

[lints]
workspace = true

[dependencies]
pinocchio = { workspace = true }
solana-hash = { workspace = true }
spl-nonce-interface = { workspace = true }
wincode = { workspace = true }

[dev-dependencies]
mollusk-svm = { workspace = true }
solana-account = { workspace = true }
solana-address = { workspace = true }
solana-instruction = { workspace = true }
solana-program-error = { workspace = true }
solana-rent = { workspace = true }
solana-sha256-hasher = { workspace = true, features = ["sha2"] }
spl-nonce-client = { workspace = true }
test-case = { workspace = true }
