[package]
name = "spl-ed25519-programmatic-signer-legacy-program"
version = "0.1.0"
description = "SPL Ed25519 Programmatic Signer program"
authors = {workspace = true}
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[lib]
crate-type = ["cdylib"]

[package.metadata.solana]
program-id = "EdSigVfK1DkeMrjFNDMjwfQaJPhPTtX7jW8uPv3oKEgN"

[lints]
workspace = true

[dependencies]
pinocchio = { workspace = true }
solana-sha256-hasher = { workspace = true, features = ["sha2"] }
spl-ed25519-programmatic-signer-legacy-interface = { workspace = true }
wincode = { workspace = true }

[dev-dependencies]
mollusk-svm = { workspace = true }
solana-account = { workspace = true }
solana-address = { workspace = true }
solana-instruction = { workspace = true }
solana-program-error = { workspace = true }
solana-rent = { workspace = true }
spl-ed25519-programmatic-signer-legacy-client = { workspace = true }
