name: Main

on:
  push:
    branches: [main]
  pull_request:

env:
  IDL_PACKAGES: "['workspace']"
  RUST_PACKAGES: "['executor-client', 'executor-interface', 'executor-program', 'nonce-client', 'nonce-interface', 'nonce-program', 'signer-client', 'signer-interface', 'signer-program']"
  SBPF_PROGRAM_PACKAGES: "['executor-program', 'nonce-program', 'signer-program']"
  NO_STD_CORE_PACKAGES: "['nonce-interface', 'nonce-program']"
  NO_STD_ALLOC_PACKAGES: "['executor-client', 'executor-interface', 'executor-program', 'nonce-client', 'signer-client', 'signer-interface', 'signer-program']"

jobs:
  set_env:
    name: Set variables to be used in strategy definitions in reusable workflow
    runs-on: ubuntu-latest
    outputs:
      IDL_PACKAGES: ${{ steps.compute.outputs.IDL_PACKAGES }}
      SBPF_PROGRAM_PACKAGES: ${{ steps.compute.outputs.SBPF_PROGRAM_PACKAGES }}
      RUST_PACKAGES: ${{ steps.compute.outputs.RUST_PACKAGES }}
      RUST_TOOLCHAIN_NIGHTLY: ${{ steps.compute.outputs.RUST_TOOLCHAIN_NIGHTLY }}
      SOLANA_CLI_VERSION: ${{ steps.compute.outputs.SOLANA_CLI_VERSION }}
      NO_STD_CORE_PACKAGES: ${{ steps.compute.outputs.NO_STD_CORE_PACKAGES }}
      NO_STD_ALLOC_PACKAGES: ${{ steps.compute.outputs.NO_STD_ALLOC_PACKAGES }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Compute variables
        id: compute
        shell: bash
        run: |
          echo "SBPF_PROGRAM_PACKAGES=$SBPF_PROGRAM_PACKAGES" >> "$GITHUB_OUTPUT"
          echo "RUST_PACKAGES=$RUST_PACKAGES" >> "$GITHUB_OUTPUT"
          echo "RUST_TOOLCHAIN_NIGHTLY=$(make rust-toolchain-nightly)" >> "$GITHUB_OUTPUT"
          echo "SOLANA_CLI_VERSION=$(make solana-cli-version)" >> "$GITHUB_OUTPUT"
          echo "NO_STD_CORE_PACKAGES=$NO_STD_CORE_PACKAGES" >> "$GITHUB_OUTPUT"
          echo "NO_STD_ALLOC_PACKAGES=$NO_STD_ALLOC_PACKAGES" >> "$GITHUB_OUTPUT"
          echo "IDL_PACKAGES=$IDL_PACKAGES" >> "$GITHUB_OUTPUT"

  main:
    needs: set_env
    uses: solana-program/actions/.github/workflows/main.yml@main
    with:
      generate-clients: false # Upcoming PR
      idl-packages: ${{ needs.set_env.outputs.IDL_PACKAGES }}
      sbpf-program-packages: ${{ needs.set_env.outputs.SBPF_PROGRAM_PACKAGES }}
      rust-packages: ${{ needs.set_env.outputs.RUST_PACKAGES }}
      rustfmt-toolchain: ${{ needs.set_env.outputs.RUST_TOOLCHAIN_NIGHTLY }}
      clippy-toolchain: ${{ needs.set_env.outputs.RUST_TOOLCHAIN_NIGHTLY }}
      solana-cli-version: ${{ needs.set_env.outputs.SOLANA_CLI_VERSION }}
      no-std-toolchain: ${{ needs.set_env.outputs.RUST_TOOLCHAIN_NIGHTLY }}
      no-std-core-packages: ${{ needs.set_env.outputs.NO_STD_CORE_PACKAGES }}
      no-std-alloc-packages: ${{ needs.set_env.outputs.NO_STD_ALLOC_PACKAGES }}
